import openai
import pandas as pd
import os
import time

API_KEY = "не будет хи хи ха"
INPUT_DIR = "data/raw"
MODEL = "gpt-4o"
SYSTEM_PROMT = (
    "You are an expert linguist and forensic analyst specializing in detecting "
    "AI-generated text. You analyze product reviews and decide whether each one was "
    "written by a real human customer or generated by an AI language model.\n\n"
    "Signs of AI-generated reviews:\n"
    "- Overly polished, generic or marketing-like language\n"
    "- Balanced, symmetric structure (lists every pro and con too neatly)\n"
    "- Lack of concrete personal details, no specific use cases or context\n"
    "- grammatically correct, too many punctuation symbols\n"
    "- Repetitive phrasing, vague praise ('great product', 'highly recommend')\n"
    "- No typos, no slang, no emotional inconsistency\n\n"
    "Signs of human reviews:\n"
    "- Specific personal anecdotes, context of use, real-life details\n"
    "- Typos, slang, inconsistent grammar, emotional tone\n"
    "- Focused on one or two things the person actually cared about\n"
    "- Irregular structure, may be very short or rambling\n\n"
    "You must answer with EXACTLY one word and nothing else: "
    "'AI' if the review is AI-generated, or 'HUMAN' if it was written by a real person. "
    "No explanations, no punctuation, no extra text."
)

text2label = {"AI": 0, "HUMAN": 1}


def _build_prompt(review_text, rating):
    return (
        "Classify the following product review as AI-generated or human-written.\n"
        "Respond with EXACTLY one word: AI or HUMAN.\n\n"
        f"Review:\n\"\"\"\n{review_text}\n\"\"\""
        f"Review rating: {rating}\n"
    )


def classify_reviews(texts, ratings=None):
    """Классифицирует отзывы через LLM. Возвращает список меток 0/1 (None при ошибке)."""
    client = openai.OpenAI(api_key=API_KEY, base_url="https://models.github.ai/inference")
    if ratings is None:
        ratings = [None] * len(texts)

    preds = []
    for ind, (review_text, rating) in enumerate(zip(texts, ratings)):
        prompt = _build_prompt(review_text, rating)
        for attempt in range(5):
            try:
                response = client.chat.completions.create(
                    model=MODEL,
                    messages=[
                        {"role": "system", "content": SYSTEM_PROMT},
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0,
                )
                label = response.choices[0].message.content.strip().upper()
                preds.append(text2label.get(label))
                print(f"[{ind + 1}/{len(texts)}] ответ: {label!r} -> {preds[-1]}")
                break
            except Exception as e:
                msg = str(e)
                if "Too many requests" in msg or "429" in msg:
                    wait = 60 * (2 ** attempt)
                    print(f"Rate limit, жду {wait}s (попытка {attempt + 1}/5)...")
                    time.sleep(wait)
                else:
                    print(f"Ошибка при запросе к api для строки {ind}: {e}")
                    preds.append(None)
                    break
        else:
            preds.append(None)
    return preds


if __name__ == "__main__":
    input_file = f"{INPUT_DIR}/pseudo_labeled_amazon_reviews.csv"
    df = pd.read_csv(input_file).fillna("")
    text_col = "text" if "text" in df.columns else "review"
    preds = classify_reviews(df[text_col].tolist(), df["rating"].tolist())
    print(preds)
